CollaborativeComics/Controllers/ComicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CollaborativeComics.Data;
using CollaborativeComics.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace CollaborativeComics.Controllers
{
    [Authorize]
    public class ComicsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ComicsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Comics
        public async Task<IActionResult> Index()
        {
            return View(await _context.Comics.ToListAsync());
        }

        // GET: Comics/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comics = await _context.Comics
                .Include(c=>c.Panels)
                .Include(c=>c.Story)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (comics == null)
            {
                return NotFound();
            }

            return View(comics);
        }

        // GET: Comics/Create
        public IActionResult Create(int? id)
        {
            if(id!=null)
                ViewData.Add("storyId", (int)id);
            return View();
        }

        // POST: Comics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? storyId, string Name, IFormFile cover)
        {
            var comics = new Comics();
            if(storyId!=null)
                comics.Story = _context.Story.First(s => s.Id == storyId);
            comics.Name = Name;

            if (cover != null)
            {
                var guid = Guid.NewGuid().ToString();
                var extension = Path.GetExtension(cover.FileName);
                comics.CoverURI = $"/covers/{guid}{extension}";

                var path = $"{Directory.GetCurrentDirectory()}\\wwwroot\\covers\\{guid}{extension}";
                using (var fs = new FileStream(path, FileMode.Create))
                {
                    await cover.CopyToAsync(fs);
                }
            }
            else comics.CoverURI = "/covers/default.jpg";

            if (ModelState.IsValid)
            {
                _context.Add(comics);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(comics);
        }

        // GET: Comics/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comics = await _context.Comics.SingleOrDefaultAsync(m => m.Id == id);
            if (comics == null)
            {
                return NotFound();
            }
            return View(comics);
        }

        // POST: Comics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IFormFile cover, [Bind("Id,Name,CoverURI")] Comics comics)
        {
            if (id != comics.Id)
            {
                return NotFound();
            }

            if (cover != null)
            {
                var guid = Guid.NewGuid().ToString();
                var extension = Path.GetExtension(cover.FileName);
                comics.CoverURI = $"/covers/{guid}{extension}";
                var path = $"{Directory.GetCurrentDirectory()}\\wwwroot\\covers\\{guid}{extension}";
                using (var fs = new FileStream(path, FileMode.Create))
                {
                    await cover.CopyToAsync(fs);
                }
            }
            else
            {
                comics.CoverURI = "/covers/default.jpg";
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comics);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComicsExists(comics.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(comics);
        }

        // GET: Comics/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comics = await _context.Comics
                .SingleOrDefaultAsync(m => m.Id == id);
            if (comics == null)
            {
                return NotFound();
            }

            return View(comics);
        }

        // POST: Comics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comics = await _context.Comics.SingleOrDefaultAsync(m => m.Id == id);
            _context.Comics.Remove(comics);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComicsExists(int id)
        {
            return _context.Comics.Any(e => e.Id == id);
        }
    }
}

CollaborativeComics/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CollaborativeComics.Data;
using Microsoft.AspNetCore.Mvc;
using CollaborativeComics.Models;

namespace CollaborativeComics.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var comicsCount = _context.Comics.Count();
            var storiesCount = _context.Story.Count();
            var panelsCount = _context.Panel.Count();
            var usersCount = _context.Users.Count();

            ViewData["comicsCount"] = comicsCount;
            ViewData["storiesCount"] = storiesCount;
            ViewData["panelsCount"] = panelsCount;
            ViewData["usersCount"] = usersCount;
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CollaborativeComics/Controllers/StoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CollaborativeComics.Data;
using CollaborativeComics.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace CollaborativeComics.Controllers
{
    [Authorize]
    public class StoriesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public StoriesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Stories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Story.ToListAsync());
        }

        // GET: Stories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var story = await _context.Story
                .Include(s=>s.Author)
                .Include(s=>s.Comics)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (story == null)
            {
                return NotFound();
            }

            return View(story);
        }

        // GET: Stories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Stories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,CreationTime,Description")] Story story)
        {
            story.CreationTime = DateTime.Now;
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser != null)
                story.Author = currentUser;

            if (ModelState.IsValid)
            {
                _context.Add(story);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(story);
        }

        // GET: Stories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var story = await _context.Story.SingleOrDefaultAsync(m => m.Id == id);
            if (story == null)
            {
                return NotFound();
            }
            return View(story);
        }

        // POST: Stories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,CreationTime,Description")] Story story)
        {
            if (id != story.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(story);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoryExists(story.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(story);
        }

        // GET: Stories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var story = await _context.Story
                .SingleOrDefaultAsync(m => m.Id == id);
            if (story == null)
            {
                return NotFound();
            }

            return View(story);
        }

        // POST: Stories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var story = await _context.Story.SingleOrDefaultAsync(m => m.Id == id);
            _context.Story.Remove(story);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StoryExists(int id)
        {
            return _context.Story.Any(e => e.Id == id);
        }
    }
}

CollaborativeComics/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CollaborativeComics/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CollaborativeComics/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img width:auto src="~/images/stories.png" alt="Истории" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p style="color:white; text-shadow: black 0 0 5px;">
                    Выбирайте истории или предлагайте новые
                    <a class="btn btn-default" asp-controller="Stories" asp-action="Index">
                        К историям
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/comics.png" alt="Комиксы" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p style="color:white; text-shadow: black 0 0 5px;">
                    Просматривайте и создавайте комиксы
                    <a class="btn btn-default" asp-controller="Comics" asp-action="Index">
                        К комиксам
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/panels.png" alt="Картинки" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p style="color: black;text-shadow:white -1px -1px 4px">
                    Совместно добавляйте картинки к комиксам
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<br/>
<style type="text/css">
    td {
        padding: 0px 5px 0px 5px;
        text-shadow: black 0 0 0.5px;
    }
</style>
<div >
    <table>
        <tr>
            <td>Зарегистрировано пользователей:</td>
            <td>@ViewData["usersCount"]</td>
        </tr>
        <tr>
            <td>Добавлено историй:</td>
            <td>@ViewData["storiesCount"]</td>
        </tr>
        <tr>
            <td>Создано комиксов:</td>
            <td>@ViewData["comicsCount"]</td>
        </tr>
        <tr>
            <td>Добавлено картинок:</td>
            <td>@ViewData["panelsCount"]</td>
        </tr>
    </table>
</div>