CollaborativeComics/Models/Comics.cs
using System.Collections.Generic;

namespace CollaborativeComics.Models
{
    public class Comics
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string CoverURI { get; set; }

        public Story Story { get; set; }

        public List<Panel> Panels { get; set; } = new List<Panel>();

    }
}

CollaborativeComics/Controllers/ComicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CollaborativeComics.Data;
using CollaborativeComics.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace CollaborativeComics.Controllers
{
    [Authorize]
    public class ComicsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ComicsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Comics
        public async Task<IActionResult> Index()
        {
            return View(await _context.Comics.ToListAsync());
        }

        // GET: Comics/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comics = await _context.Comics
                .Include(c=>c.Panels)
                .Include(c=>c.Story)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (comics == null)
            {
                return NotFound();
            }

            return View(comics);
        }

        // GET: Comics/Create
        public IActionResult Create(int? id)
        {
            if(id!=null)
                ViewData.Add("storyId", (int)id);
            return View();
        }

        // POST: Comics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? storyId, string Name, IFormFile cover)
        {
            var comics = new Comics();
            if(storyId!=null)
                comics.Story = _context.Story.First(s => s.Id == storyId);
            comics.Name = Name;

            if (cover != null)
            {
                var guid = Guid.NewGuid().ToString();
                var extension = Path.GetExtension(cover.FileName);
                comics.CoverURI = $"/covers/{guid}{extension}";

                var path = $"{Directory.GetCurrentDirectory()}\\wwwroot\\covers\\{guid}{extension}";
                using (var fs = new FileStream(path, FileMode.Create))
                {
                    await cover.CopyToAsync(fs);
                }
            }
            else comics.CoverURI = "/covers/default.jpg";

            if (ModelState.IsValid)
            {
                _context.Add(comics);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(comics);
        }

        // GET: Comics/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comics = await _context.Comics.SingleOrDefaultAsync(m => m.Id == id);
            if (comics == null)
            {
                return NotFound();
            }
            return View(comics);
        }

        // POST: Comics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IFormFile cover, [Bind("Id,Name,CoverURI")] Comics comics)
        {
            if (id != comics.Id)
            {
                return NotFound();
            }

            if (cover != null)
            {
                var guid = Guid.NewGuid().ToString();
                var extension = Path.GetExtension(cover.FileName);
                comics.CoverURI = $"/covers/{guid}{extension}";
                var path = $"{Directory.GetCurrentDirectory()}\\wwwroot\\covers\\{guid}{extension}";
                using (var fs = new FileStream(path, FileMode.Create))
                {
                    await cover.CopyToAsync(fs);
                }
            }
            else
            {
                comics.CoverURI = "/covers/default.jpg";
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comics);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComicsExists(comics.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(comics);
        }

        // GET: Comics/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comics = await _context.Comics
                .SingleOrDefaultAsync(m => m.Id == id);
            if (comics == null)
            {
                return NotFound();
            }

            return View(comics);
        }

        // POST: Comics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comics = await _context.Comics.SingleOrDefaultAsync(m => m.Id == id);
            _context.Comics.Remove(comics);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComicsExists(int id)
        {
            return _context.Comics.Any(e => e.Id == id);
        }
    }
}

CollaborativeComics/Controllers/PanelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CollaborativeComics.Data;
using CollaborativeComics.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace CollaborativeComics.Controllers
{
    [Authorize]
    public class PanelsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PanelsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Panels
        private async Task<IActionResult> Index()
        {
            return View(await _context.Panel.ToListAsync());
        }

        // GET: Panels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panel = await _context.Panel
                .Include(p=>p.Comics)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (panel == null)
            {
                return NotFound();
            }

            return View(panel);
        }

        // GET: Panels/Create
        public IActionResult Create(int? id)
        {
            ViewData["comicsId"] = id;
            return View();
        }

        // POST: Panels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? comicsId, IFormFile image, string description)
        {
            var panel = new Panel();

            panel.Comics = _context.Comics.FirstOrDefault(c => c.Id == comicsId);
            panel.Description = description;
            panel.LastUpdate = DateTime.Now;
            if (image != null)
            {
                var guid = Guid.NewGuid().ToString();
                var extension = Path.GetExtension(image.FileName);
                panel.ImageURI = $"/panels/{guid}{extension}";
                var path = $"{Directory.GetCurrentDirectory()}\\wwwroot\\panels\\{guid}{extension}";
                using (var fs = new FileStream(path, FileMode.Create))
                {
                    await image.CopyToAsync(fs);
                }
            }
            else
            {
                panel.ImageURI = "/panels/default.jpg";
            }

            if (ModelState.IsValid)
            {
                _context.Panel.Add(panel);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Comics", new{id=panel.Comics?.Id});
                //return RedirectToAction(nameof(Index));
            }
            return View("Create");
        }

        // GET: Panels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panel = await _context.Panel.Include(p=>p.Comics).SingleOrDefaultAsync(m => m.Id == id);
            if (panel == null)
            {
                return NotFound();
            }
            return View(panel);
        }

        // POST: Panels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IFormFile image, [Bind("Id,LastUpdate,ImageURI,Description")] Panel panel)
        {
            if (id != panel.Id)
            {
                return NotFound();
            }

            panel.LastUpdate = DateTime.Now;

            if (image != null)
            {
                var guid = Guid.NewGuid().ToString();
                var extension = Path.GetExtension(image.FileName);
                panel.ImageURI = $"/panels/{guid}{extension}";
                var path = $"{Directory.GetCurrentDirectory()}\\wwwroot\\panels\\{guid}{extension}";
                using (var fs = new FileStream(path, FileMode.Create))
                {
                    await image.CopyToAsync(fs);
                }
            }
            else
            {
                panel.ImageURI = "/panels/default.jpg";
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(panel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PanelExists(panel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(panel);
        }

        // GET: Panels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var panel = await _context.Panel
                .Include(p=>p.Comics)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (panel == null)
            {
                return NotFound();
            }

            return View(panel);
        }

        // POST: Panels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var panel = await _context.Panel.Include(p=>p.Comics).SingleOrDefaultAsync(m => m.Id == id);
            _context.Panel.Remove(panel);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Comics", new {id = panel.Comics?.Id});
        }

        private bool PanelExists(int id)
        {
            return _context.Panel.Any(e => e.Id == id);
        }
    }
}

CollaborativeComics/Controllers/StoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CollaborativeComics.Data;
using CollaborativeComics.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace CollaborativeComics.Controllers
{
    [Authorize]
    public class StoriesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public StoriesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Stories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Story.ToListAsync());
        }

        // GET: Stories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var story = await _context.Story
                .Include(s=>s.Author)
                .Include(s=>s.Comics)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (story == null)
            {
                return NotFound();
            }

            return View(story);
        }

        // GET: Stories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Stories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,CreationTime,Description")] Story story)
        {
            story.CreationTime = DateTime.Now;
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser != null)
                story.Author = currentUser;

            if (ModelState.IsValid)
            {
                _context.Add(story);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(story);
        }

        // GET: Stories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var story = await _context.Story.SingleOrDefaultAsync(m => m.Id == id);
            if (story == null)
            {
                return NotFound();
            }
            return View(story);
        }

        // POST: Stories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,CreationTime,Description")] Story story)
        {
            if (id != story.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(story);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoryExists(story.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(story);
        }

        // GET: Stories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var story = await _context.Story
                .SingleOrDefaultAsync(m => m.Id == id);
            if (story == null)
            {
                return NotFound();
            }

            return View(story);
        }

        // POST: Stories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var story = await _context.Story.SingleOrDefaultAsync(m => m.Id == id);
            _context.Story.Remove(story);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StoryExists(int id)
        {
            return _context.Story.Any(e => e.Id == id);
        }
    }
}

CollaborativeComics/Views/Comics/Create.cshtml
@model CollaborativeComics.Models.Comics

@{
    ViewData["Title"] = "Создать комикс";
}
<h2>Создать комикс</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="storyId" value=@ViewData["storyId"] type="hidden" />
            <div class="form-group">
                <label >Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="file" name="cover" />
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку комиксов</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CollaborativeComics/Views/Comics/Delete.cshtml
@model CollaborativeComics.Models.Comics

@{
    ViewData["Title"] = "Delete";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить историю?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            Название
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Обложка
        </dt>
        <dd>
            <img src=@Model.CoverURI width="100"/>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-default" /> |
        <a asp-action="Index">Назад к списку комиксов</a>
    </form>
</div>

CollaborativeComics/Views/Comics/Details.cshtml
@model CollaborativeComics.Models.Comics

@{
    ViewData["Title"] = "Details";
}

<h2>Сведения о комиксе</h2>

<div>
       <hr />
    <dl class="dl-horizontal">
        <dt>
           Название
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            <img src=@Model.CoverURI width="100" />
        </dt>
        <dd>
            @if (Model.Story != null)
            {
                <a asp-controller="Stories" asp-action="Details" asp-route-id=@Model.Story?.Id>История</a>
            }
        </dd>
    </dl>
</div>
<a asp-controller="Panels" asp-action="Create" asp-route-id=@Model.Id>Создать картинку</a>
<table class="table">
    <thead>
        <tr>
            <th>
                Картинка
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Panels ?? new List<Panel>())
        {
            <tr>
                <td>
                    <img src=@item.ImageURI height="100" alt=@item.Description/>
                </td>
                <td>
                    <a asp-action="Edit" asp-controller="Panels" asp-route-id="@item.Id">Редактировать</a> |
                    <a asp-action="Details" asp-controller="Panels" asp-route-id="@item.Id">Посмотреть</a> |
                    <a asp-action="Delete" asp-controller="Panels" asp-route-id="@item.Id">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Редактировать</a> |
    <a asp-action="Index">Назад к списку комиксов</a>
</div>

CollaborativeComics/Views/Comics/Edit.cshtml
@model CollaborativeComics.Models.Comics

@{
    ViewData["Title"] = "Edit";
}

<h2>Редактировать комикс</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            
            <div class="form-group">
                <label>Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Картинка</label>
                <img src=@Model.CoverURI width="100" />
                <input type="file" name="cover" value="Загрузить новую" />
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку комиксов</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CollaborativeComics/Views/Comics/Index.cshtml
@model IEnumerable<CollaborativeComics.Models.Comics>

@{
    ViewData["Title"] = "Index";
}

<h2>Комиксы</h2>


<table class="table">
    <thead>
        <tr>
                <th>
                    Название
                </th>
                <th>
                    Обложка
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <img src=@item.CoverURI height="100" />
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Посмотреть</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>